disabled_rules: # rule identifiers to exclude from running
 - cyclomatic_complexity
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
 - Routine/R.generated.swift
 
